# au majy<majiayang@zuozh.com>:
nginx:
        container_name: "nginx"
        restart: "unless-stopped"
        image: docker.io/nginx:latest
        ports:
                - "80:80"
        volumes:
            - ./html:/var/www/
            - ./conf.d:/etc/nginx/conf.d/
redis:
        container_name: "redis"
        restart: "unless-stopped"
        image: docker.io/redis:latest
        volumes:
            - ./redis:/var/redis/
        ports:
                - "6379:6379"
        command: redis-server /var/redis/redis.conf
hell:
        container_name: "hell"
        restart: "unless-stopped"
        image: scx/jdk:latest
        volumes:
            - ./hell/:/var/jar/
            - ./tester/:/var/project/tester/
        links:
            - redis:redis.sxc.com
        command: java -jar /var/jar/hell.jar