wealth:
        container_name: "wealth"
        restart: "UNLESS-STOP"
        image: zzjr/tomcat:latest
        volumes:
                - ./tomcat/wealth/:/usr/local/tomcat/webapps/
                - ./logs/wealth/:/usr/local/tomcat/logs/
        links:
                - mysql:db.niubangold.com
                - redis:redis.niubangold.com
        command: /usr/local/tomcat/bin/catalina.sh run
mysql:
        container_name: "mysql"
        restart: "UNLESS-STOP"
        image: zzjr/mysql:latest
        volumes:
                - ./mysql/data/:/var/lib/mysql/
        ports:
                - "3306:3306"
        command: /usr/bin/mysqld_safe
redis:
        container_name: "redis"
        restart: "UNLESS-STOP"
        image: zzjr/redis:latest
        command: redis-server
