# au majy<majiayang@zuozh.com>
wealth:
        container_name: "wealth"
        restart: "UNLESS-STOP"
        image: zzjr/tomcat:latest
        volumes:
                - ./tomcat/wealth/:/usr/local/tomcat/webapps/
                - ./tomcat/wealth_conf/:/usr/local/tomcat/conf/properties/
                - ./logs/wealth/:/usr/local/tomcat/logs/
        links:
                - mysql:db.majiayang.com
                - redis:redis.majiayang.com
                - zookeeper:zk.majiayang.com
        command: /usr/local/tomcat/bin/catalina.sh run
pms:
        container_name: "pms"
        restart: "UNLESS-STOP"
        image: zzjr/tomcat:latest
        volumes:
                - ./tomcat/pms/:/usr/local/tomcat/webapps/
                - ./logs/pms/:/usr/local/tomcat/logs/
                - ./tomcat/properties/pms/:/usr/local/tomcat/conf/properties/
        links:
                - mysql:db.majiayang.com
                - redis:redis.majiayang.com
                - zookeeper:zk.majiayang.com
        command: /usr/local/tomcat/bin/catalina.sh run
rap:
        container_name: "rap"
        restart: "UNLESS-STOP"
        image: zzjr/tomcat:latest
        volumes:
                - ./tomcat/rap/:/usr/local/tomcat/webapps/
                - ./logs/rap/:/usr/local/tomcat/logs/
        links:
                - mysql:db.majiayang.com
                - redis:redis.majiayang.com
        command: /usr/local/tomcat/bin/catalina.sh run
mldp:
        container_name: "mldp"
        restart: "UNLESS-STOP"
        image: zzjr/tomcat:latest
        volumes:
                - ./tomcat/mldp/:/usr/local/tomcat/webapps/
                - ./logs/mldp/:/usr/local/tomcat/logs/
                - ./tomcat/properties/mldp/:/usr/local/tomcat/conf/properties/
        links:
                - mysql:db.majiayang.com
                - redis:redis.majiayang.com
                - zookeeper:zk.majiayang.com
        ports:
                - "8080:8080"
        links:
                - redis:reds.majiayang.com
                - mysql:mysql.majiayang.com
        command: /usr/local/tomcat/bin/catalina.sh run
mysql:
        container_name: "mysql"
        restart: "UNLESS-STOP"
        image: zzjr/mysql:latest
        volumes:
                - ./mysql/data/:/var/lib/mysql/
        ports:
                - "3306:3306"
        command: sh /root/pkg/start.sh
redis:
        container_name: "redis"
        restart: "UNLESS-STOP"
        image: zzjr/redis:latest
        command: redis-server
zookeeper:
        container_name: "zookeeper"
        restart: "UNLESS-STOP"
        image: zzjr/zookeeper:latest
        command: sh /root/pkg/start.sh
nginx:
        container_name: "nginx"
        restart: "UNLESS-STOP"
        image: zzjr/nginx:latest
        volumes:
                - ./logs/nginx/:/usr/local/nginx/logs/
        expose: 
                - "80"
        ports:
                - "80:80"
        links:
#                - wealth:wealth
#                - pms:pms
#                - mldp:mldp
                - rap:rap.majiayang.com
        command: sh /root/pkg/start.sh
