jenkins:
        container_name: "jenkins"
        restart: "UNLESS-STOP"
        image: zzjr/jenkins:latest
        ports:
        - "50000:50000"
        - "8080:8080"
        volumes:
        - ./jenkins_home:/var/jenkins_home
        - ./ssh/:/root/.ssh