mysql:
        container_name: "mysql"
        restart: "UNLESS-STOP"
        image: "docker.io/mysql:latest"
        volumes:
                - ./data/:/var/lib/mysql/
        ports:
                - "3306:3306"
        environment:
                - MYSQL_ROOT_PASSWORD=123456