# au majy<majiayang@zuozh.com>
redis:
        container_name: "redis"
        restart: "no"
        image: docker.io/redis:latest
        ports:
                - "8080:8080"
        command: redis-server
